apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flink
      component: jobmanager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flink
        component: jobmanager
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: jobmanager
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/jobmanager.sh start;\
          while :;
          do
            if [[ -f $(find log -name '*jobmanager*.log' -print -quit) ]];
              then tail -f -n +1 log/*jobmanager*.log;
            fi;
          done"]
        env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-flink
              key: s3AccessKey
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-flink
              key: s3SecretKey
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 10
          periodSeconds: 20
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        securityContext:
          runAsUser: 9999
      volumes:
      - name: flink-config-volume
        configMap:
          name: {{ .Release.Name }}-flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
