apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flink-taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flink
        component: taskmanager
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: taskmanager
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/taskmanager.sh start; \
          while :;
          do
            if [[ -f $(find log -name '*taskmanager*.log' -print -quit) ]];
              then tail -f -n +1 log/*taskmanager*.log;
            fi;
          done"]
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-flink
              key: s3AccessKey
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-flink
              key: s3SecretKey
        ports:
        - containerPort: 6122
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        securityContext:
          runAsUser: 9999
      volumes:
      - name: flink-config-volume
        configMap:
          name: {{ .Release.Name }}-flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
