# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

taskmanager:
  replicaCount: 2

ha:
  # default: "NONE"
  mode: de.thmshmm.flink.ha.k8s.KubernetesHAServicesFactory
  storageDir: s3p://flink-ha/
  kubernetes:
    namespace: flink-ha

image:
  name: flink-custom:1.10.0-scala_2.12-1
  pullPolicy: Never

s3:
  endpoint: http://sunny-minio:9000
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

